# Copyright 2020 Pants project contributors.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# See https://pants.readme.io/docs/using-pants-in-ci for tips on how to set up your CI with Pants.

env:
  global:
    - PANTS_CONFIG_FILES=pants.ci.toml

os: linux
dist: bionic
language: python
python: 3.7

cache:
  directories:
    - $HOME/.cache/pants/setup
    - $HOME/.cache/pants/lmdb_store

install:
  - ./pants --version  # This will bootstrap Pants

script:
  - ./pants lint test '**'
  # Smoke test that our release process will work.
  - ./pants binary helloworld/main.py helloworld/main_py2.py
  - ./pants run helloworld/main.py
  - ./pants run helloworld/main_py2.py
  - ./pants setup-py --args="bdist_wheel" helloworld/util:dist
  - ./pants awslambda helloworld:helloworld-awslambda
