# Copyright 2020 Pants project contributors.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# See https://pants.readme.io/docs/using-pants-in-ci for tips on how to set up your CI with Pants.

env:
  global:
    - PANTS_CONFIG_FILES=pants.ci.toml

os: linux
dist: bionic
language: python
python: 3.7

cache:
  directories:
    - $HOME/.cache/pants/setup
    - $HOME/.cache/pants/lmdb_store
    - $HOME/.cache/pants/named_caches

install:
  - ./pants --version  # Bootstrap Pants.

script:
  # We also smoke test that our release process will work by running `package`.
  - ./pants lint typecheck test package '::'
  - ./pants run helloworld/main.py
