# Copyright 2020 Pants project contributors.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

[GLOBAL]
pants_version = "2.0.0.dev2"
pantsd = true  # Enable the Pants daemon for better performance.

# List backends here.
backend_packages.add = [
  'pants.backend.awslambda.python',
  'pants.backend.codegen.protobuf.python',
  'pants.backend.python',
  'pants.backend.python.lint.docformatter',
  'pants.backend.python.lint.black',
  'pants.backend.python.lint.flake8',
  'pants.backend.python.lint.isort',
]

# List plugins here.
plugins = []

[source]
# The Python source root is the repo root. See https://pants.readme.io/docs/source-roots.
root_patterns = ["/"]

[python-setup]
# The default interpreter compatibility for code in this repo. Individual targets can ovverride
#  this with the `compatibility` field. See
#  https://pants.readme.io/docs/python-interpreter-compatibility.
interpreter_constraints = [">=3.7"]
# Use a lockfile. See https://pants.readme.io/docs/python-third-party-dependencies.
requirement_constraints = "constraints.txt"

[protoc]
runtime_targets = ["//:protobuf"]

[flake8]
config = ".flake8"

[isort]
config = [".isort.cfg"]
